package DNA_counting_nucleotides;

import org.junit.Test;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;
/**
 * Created by Oleg Grigorjev on 26.06.2016.
 */
public class NucleotidesCounterTest {

    @Test
    public void printOutput() throws Exception {
        NucleotidesCounter counter = new NucleotidesCounter("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC");
        assertThat(counter.getResult(), is("20 12 17 21"));
        counter = new NucleotidesCounter("TCACAAGGTCTCTGGTATAGTGGGGGCAGTTCCCATTCTTGCCGCTGTGTCTTACCCGGCCCCGACTATTTTGCTGGCACTTCTTGCAGTAACCTTCGCCTTTATTCTACACTAGAGGGTCTTGTCTCACACCGGGTGACTGCAGCGACTTAGATACATTATTCGGCGGTTTCCTACGAGTGATCGCACCCTATCTCTTATGACATAAATATCGCAATTTAGCTGGTATTACGTCGTAAATACAGGCTGGATTACGCGGTGAGGCTTACGGCGCGGGCGTCCCCGATTATGGATCTTACTACCCTTGTCCTGGAGGAAGAATGAACAACTGCTTCCGTTGAGCGTTGTAACTGCCATGCTGTAGCAGCGACCGGGAGACGTAGCCGGTAGTAGACATTACCTTACTGCCTGGCAGATACGGAGGAGAACCACTAGTTTTGCAGTTGGCATAGCTTAAATAGAAATCAATACGCACTTAACGACCCGAGCGTAGGCGAACCTCATTTTAAAAAACTAGTTGCCAGTCGCAAATTAGGGGTCCTAAAGAGAACGGCGTTTTCTTGAACGCGGTCGTTTCTCTAAGCAGAATGGATACATCTAATGCTCCCATTGGCCTGCGGCGCGATCCCTATAGCTGGCCGGCGCCTCCCGACACGACATCGATAACCCGGAATTTGCCCCCGTGCAAATTAGTATAGGCATAAACGAATTTGATTGCACGAGTGCATACTTGTAACTCATAATATTCAATATCTTAGAGGTCACGTTCCAATAAAGGACTATGATATCCTGGAATGAGACGCCCTGTCTCCGGAAACGGCCAGTCGAAAGGATATCATTGCACCCCAACAGTGTACAAGAACGAGTGTTACTCTTCGACTCTTAAGATGCATTTTAACTGCGGTATGCATAAAACACAAGCGCGAATAATGGAAGTCAGACGAC");
        assertThat(counter.getResult(), is("247 232 222 244"));
    }
}